---
name: module3_task0
# Events that trigger workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"  # Download code from the repository
        uses: actions/checkout@v3

      - name: "Run make help"  # Execute the command make help
        run: cd module3_task0 && make help
