---
name: module3_task1
# Events that trigger workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"  # Download code from the repository
        uses: actions/checkout@v3

      - name: "Run bash script"
        run: cd module3_task1 && ./setup.sh

      - name: "Run make build"  # Execute the command make build
        run: cd module3_task1 && make build
